language: objective-c
osx_image: xcode8
script:
  - xcodebuild -project Truckfeed/TruckFeed.xcworkspace -scheme TruckFeed -sdk iphonesimulator 
  - xcodebuild -project Truckfeed/TruckFeed.xcworkspace -scheme TruckFeedTests -sdk iphonesimulator 
