language: objective-c
branches:
 only:
 - master
osx_image: xcode7.3
script:
  - xcodebuild -project Truckfeed/TruckFeed.xcodeproj -scheme TruckFeed -sdk iphonesimulator 
  - xcodebuild -project Truckfeed/TruckFeed.xcodeproj -scheme TruckFeedTests -sdk iphonesimulator 
