language: objective-c
 
branches:
 only:
 - master
script:
  - xctool -project Truckfeed/TruckFeed.xcodeproj -scheme Truckfeed 
  - xctool test -project Truckfeed/TruckFeed.xcodeproj -scheme TruckFeedTests