# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'TruckFeed' do
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
end

target 'TruckFeedTests' do
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
end

