# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TruckFeed' do
  use_frameworks!

  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  
  # Pods for TruckFeed

  target 'TruckFeedTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TruckFeedUITests' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TruckFeedUITests

end
